info:
  app:
    version: 2.2.0.M4
    name: drools

server:
  port: 8097

spring:
  application:
    name: drools-service
#  profiles:
#    active: @spring.profiles.active@
eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.consul: DEBUG
