info:
  app:
    version: 2.2.0.M4
    name: gateway

server:
  port: 8091

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /health
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 应用名称+服务器IP+端口
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            # This route rule used to forward request to activity server
      - id: test-route
      uri: http://localhost:8090
      predicates:
        - Path=/test/**
      filters:
        - StripPrefix=1
#  Gateway默认转发是全路径的，设置StripPrefix=1表示从二级url路径转发，即http://localhost:port/activity/test将会转发到http://{activity}/test

logging:
  level:
    org.springframework.cloud.consul: DEBUG
