info:
  app:
    version: 2.2.0.M4
    name: drools

server:
  port: 8097

spring:
  application:
    name: drools-service
#  profiles:
#    active: @spring.profiles.active@
  datasource:
    url: jdbc:mysql://localhost:3306/test?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: hukaijia
    password: Hukaijia.110

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



logging:
  level:
    org.springframework.cloud.consul: DEBUG
